### ISSUE TITLE
The hot-reload mechanism and node_modules can cause "Too many open files"

### ISSUE THREAD

**Issue by Philip-Scott** [SteamDeckHomebrew/PluginLoader#31]
Looks like developing a plugin with node_modules inside of the plugins folder can cause the loader to die a bit on the inside :laughing: I'm not sure what the best solution could be here.... Should we allow passing in either an watch or ignore lists to the hot-reloader? I'm open for suggestions and could help implement either option here :)

```
OSError: [Errno 24] Too many open files
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/home/deck/PluginLoader/plugin_loader/loader.py", line 194, in refresh_iframe
    await tab.open_websocket()
  File "/home/deck/PluginLoader/plugin_loader/injector.py", line 20, in open_websocket
  File "/usr/lib/python3.10/site-packages/aiohttp/client.py", line 776, in _ws_connect
  File "/usr/lib/python3.10/site-packages/aiohttp/client.py", line 535, in _request
  File "/usr/lib/python3.10/site-packages/aiohttp/connector.py", line 542, in connect
  File "/usr/lib/python3.10/site-packages/aiohttp/connector.py", line 907, in _create_connection
  File "/usr/lib/python3.10/site-packages/aiohttp/connector.py", line 1206, in _create_direct_connection
  File "/usr/lib/python3.10/site-packages/aiohttp/connector.py", line 1175, in _create_direct_connection
  File "/usr/lib/python3.10/site-packages/aiohttp/connector.py", line 992, in _wrap_create_connection
```
-----------------------------
If anyone else were to hit this, you can disable hot-reloading from the main.py file :)

**Comment by Philip-Scott** [comment]
I'm just going to close this. It was a bit annoying when it crashed, but it shouldn't really be an issue

**Comment by marios8543** [comment]
Hmm this is a wild guess but it might be because I'm using the polling observer in watchdog, so it has to check all the files for modifications. Can't be helped though since the other observer was buggy and would fire duplicate events. Maybe we can add separate modification observers that only listen to the main.py files, although I don't remember if watchdog supports this, will look into it later.
